# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "CI: semantic release"

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build_and_release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v2

      - name: "#1: install dependencies"
        run: yarn install
        
      - name: "#2: Building dApp"
        env:
          CI: true
        run: yarn run ci:build:mainnet
        
      - name: "#3: Running semantic-release"
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
